const fs = require('fs');
const envVars = `
# these are only generated on netlify deploy
NEXT_PUBLIC_BASE_URL=${process.env.NEXT_PUBLIC_BASE_URL}
NEXT_PUBLIC_MAPBOX_API_KEY=${process.env.NEXT_PUBLIC_MAPBOX_API_KEY}
NEXT_PUBLIC_MAP_BOUNDING_BOX=${process.env.NEXT_PUBLIC_MAP_BOUNDING_BOX}
NEXT_PUBLIC_MAPBOX_TREES_TILESET_URL=${process.env.NEXT_PUBLIC_MAPBOX_TREES_TILESET_URL}
NEXT_PUBLIC_MAPBOX_TREES_TILESET_LAYER=${process.env.NEXT_PUBLIC_MAPBOX_TREES_TILESET_LAYER}
NEXT_PUBLIC_AUTH0_DOMAIN=${process.env.NEXT_PUBLIC_AUTH0_DOMAIN}
NEXT_PUBLIC_AUTH0_CLIENT_ID=${process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID}
NEXT_PUBLIC_AUTH0_AUDIENCE=${process.env.NEXT_PUBLIC_AUTH0_AUDIENCE}
NEXT_PUBLIC_USER_DATA_API_URL=${process.env.NEXT_PUBLIC_USER_DATA_API_URL}
NEXT_PUBLIC_API_ENDPOINT=${process.env.NEXT_PUBLIC_API_ENDPOINT}
`;
fs.writeFileSync('./.env', envVars);
