export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_SIDEBAR = "SET_SIDEBAR";
export const SET_WATERED_TREES = "SET_WATERED_TREES";
export const SET_SELECTED_TREE_DATA = "SET_SELECTED_TREE_DATA";
export const SET_SELECTED_TREE_DATA_LOADING = "SET_SELECTED_TREE_DATA_LOADING";
export const SET_WATERED_TREES_FETCHED = "SET_WATERED_TREES_FETCHED";
export const SET_WATERING_TREE = "SET_WATERING_TREE";
export const SET_DATA_LOADED = "SET_DATA_LOADED";