export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_SELECTED_TREE_DATA = "SET_SELECTED_TREE_DATA";
export const SET_SELECTED_TREE_DATA_LOADING = "SET_SELECTED_TREE_DATA_LOADING";
export const SET_SIDEBAR = "SET_SIDEBAR";