name: Linting and Unit Tests
permissions:
  contents: write
  packages: write
on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
jobs:
  lint-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ⬇️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, pinned to commit sha to avoid sha-hulud like attacks

      - name: Setup Node.js using .nvmrc ⚙️
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0, pinned to commit sha to avoid sha-hulud like attacks
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Cache npm dependencies 💾
        id: cache-npm-deps
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0, pinned to commit sha to avoid sha-hulud like attacks
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 📦
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Check Prettier 🧹
        run: npm run prettier:ci

      - name: Check Lint 🔎
        run: npm run lint

      - name: Run Unit Tests 🧪
        run: npm run test:unit
