name: Update Pumps in Supabase Storage (development)

on:
  push:
    branches: 'feat/fetch-pumpen-from-supabase'
  workflow_dispatch: {}
  repository_dispatch:
    # This action can be triggered via Github API webook (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch)
    types: [pumps_cron]
              
jobs:
  rain:
    environment: staging
    runs-on: ubuntu-latest
    name: Aggregate pumps data and push to Supabase
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Aggregate pumps data and push to Supabase
        uses: ./.github/.workflows/upload_pumps.yml
        id: pumps
        with:
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_DATA_ASSETS_BUCKET: ${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
