name: DWD Radolan Harvester Manual Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (e.g. development or production)"
        required: true
        type: string
      dwd_harvester_version:
        description: "Version of the DWD Harvester Docker Image"
        required: true
        type: string

jobs:
  rain:
    # Using the payload of the repository_dispatch webhook to specify the environment
    environment: "${{ github.event.inputs.environment }}"
    runs-on: ubuntu-latest
    name: Aggregate rain data from DWD radolan
    steps:
      - name: Harvester
        uses: "technologiestiftung/giessdenkiez-de-dwd-harvester@${{ github.event.inputs.dwd_harvester_version }}"
        id: harvester
        with:
          PG_SERVER: ${{ secrets.PG_SERVER }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_DB: ${{ secrets.PG_DB }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_BUCKET_NAME: ${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OUTPUT: "True"
          LOGGING: "INFO"
          MAPBOXUSERNAME: ${{ secrets.MAPBOXUSERNAME }}
          MAPBOXTOKEN: ${{ secrets.MAPBOXTOKEN }}
          MAPBOXTILESET: ${{ secrets.MAPBOXTILESET }}
          MAPBOXLAYERNAME: ${{ secrets.MAPBOXLAYERNAME }}
          SKIP_MAPBOX: "False"
          LIMIT_DAYS: ${{ vars.LIMIT_DAYS }}
          SURROUNDING_SHAPE_FILE: ${{ vars.SURROUNDING_SHAPE_FILE }}
