name: Upload pumps data to Supabase
on:
  workflow_call:
    inputs:
      SUPABASE_URL:
        required: true
        type: string
      SUPABASE_DATA_ASSETS_BUCKET:
        required: true
        type: string
      SUPABASE_ACCESS_TOKEN:
        required: true
        type: string
jobs:
  pumps:
    runs-on: ubuntu-latest
    name: Aggregate pumps data from open street maps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Pumps data generate step
        id: pumps
        uses: technologiestiftung/giessdenkiez-de-osm-pumpen-harvester@v1.4.1
        with:
          outfile-path: 'public/data/pumps.geojson'
      - name: File output
        run: echo "The file was written to ${{ steps.pumps.outputs.file }}"
      - name: Upload file to supabase
        run: |
          getStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET \
            ${{ inputs.SUPABASE_URL }}/storage/v1/object/info/public/${{ inputs.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
          if [ "$getStatusCode" = "200" ]; then
            putStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
              -X PUT \
              -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
              -H "Content-Type: application/geo+json" \
              -d "@${{ steps.pumps.outputs.file }}" \
              ${{ inputs.SUPABASE_URL }}/storage/v1/object/${{ inputs.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
            if [ "$putStatusCode" = "200" ]; then
              echo "Uploading to Supabase successful"
            else
              echo "Uploading to Supabase failed"
              exit 1
            fi
          else
            postStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
              -X POST \
              -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
              -H "Content-Type: application/geo+json" \
              -d "@${{ steps.pumps.outputs.file }}" \
              ${{ inputs.SUPABASE_URL }}/storage/v1/object/${{ inputs.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
            if [ "$postStatusCode" = "200" ]; then
              echo "Uploading to Supabase successful"
            else
              echo "Uploading to Supabase failed"
              exit 1
            fi
          fi